[package]
name = "gsn2x"
description = "Tool to create graphical representations of Goal Structuring Notations from YAML."
authors = ["Jonas Wolf <jonas.wolf@jonaswolf.org>"]
version = "1.3.0"
edition = "2021"
license = "CC-BY-4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tera = "1.12"
