[package]
name = "gsn2x"
description = "Tool to create a graphical representation from a Goal Structuring Notation in YAML format."
authors = ["Jonas Wolf <jonas.wolf@jonaswolf.org>"]
version = "2.0.0"
edition = "2021"
license = "CC-BY-4.0"
repository = "https://github.com/jonasthewolf/gsn2x"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "3.1", features = ["cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirgraphsvg = { path="dirgraphsvg"}

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"