[package]
name = "gsn2x"
description = "Tool to create graphical representations of Goal Structuring Notations from YAML."
authors = ["Jonas Wolf <jonas.wolf@jonaswolf.org>"]
version = "2.0.0"
edition = "2021"
license = "CC-BY-4.0"
repository = "https://github.com/jonasthewolf/gsn2x"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[dependencies.tera]
version = "1.15"
default-features = false

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"