name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Annotate commit with clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  build_test_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Release build
      run: cargo build --release --verbose
    - name: Test
      run: cargo test --verbose
    - name: Strip binaries
      if: hashFiles('target/release/gsn2x')
      run: strip target/release/gsn2x
    - name: Strip binaries (Windows)
      if: hashFiles('target/release/gsn2x.exe')
      run: strip target/release/gsn2x.exe
    - name: Deploy to github.com
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{ matrix.os }}"
        prerelease: true
        title: "Latest Build for ${{ matrix.os }}"
        files: |
          target/release/gsn2x
          target/release/gsn2x.exe

  coverage:
    needs: build_test_deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # coverage measurement needs a nightly toolchain with llvm-tools
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: llvm-tools-preview
    - name: Coverage measurement
      continue-on-error: true
      run: |
         mkdir coverage
         cargo +nightly install cargo-llvm-cov
         cargo +nightly llvm-cov --no-report --tests
         cargo +nightly llvm-cov run --no-report -- example.gsn.yaml
         cargo +nightly llvm-cov --no-run --lcov --output-path=coverage/coverage.lcov
    - name: Upload to codecov
      uses: codecov/codecov-action@v1
      with:
        directory: coverage


